# Generated by Django 4.0.4 on 2022-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('webreq', models.IntegerField(blank=True, null=True)),
                ('timespent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
